{
 "title": "PV Snapshot",
 "description": "Minimal system data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Grid Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Sunny Boy 1 Power (W)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"pv_data\")\n|>range(start:-5m)\n|>filter(fn: (r) => r._measurement == \"pv_ac_measurements\" and r._field == \"grid_total_watts\" and r.inv_id == \"sunnyboy1\")\n|>last()"
    }
   ]
  },
  {
   "title": "Current Sunny Boy 2 Power (W)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"pv_data\")\n|>range(start:-5m)\n|>filter(fn: (r) => r._measurement == \"pv_ac_measurements\" and r._field == \"grid_total_watts\" and r.inv_id == \"sunnyboy2\")\n|>last()"
    }
   ]
  },
  {
   "title": "Current Sunny Island Master Power (W)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"pv_data\")\n|>range(start:-10m)\n|>filter(fn: (r) => r._measurement == \"ac_measurements\" and r._field == \"simaster_watts\")\n|>last()"
    }
   ]
  },
  {
   "title": "Sunny Boy 1 Today",
   "type": "stat",
   "description": "Total power produced by Sunny Boy 1 today",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "get", "keyName": "pv_total_sunnyboy1", "type": "command" }
   ]
  },
  {
   "title": "Sunny Boy 2 Today",
   "type": "stat",
   "description": "Total power produced by Sunny Boy 1 today",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "get", "keyName": "pv_total_sunnyboy2", "type": "command" }
   ]
  },
  {
   "title": "Current Sunny Island Slave 1 Power (W)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"pv_data\")\n|>range(start:-10m)\n|>filter(fn: (r) => r._measurement == \"ac_measurements\" and r._field == \"sislave1_watts\")\n|>last()"
    }
   ]
  },
  {
   "title": "L1 Voltage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"pv_data\")\n|>range(start:-10m)\n|>filter(fn: (r) => r._measurement == \"ac_measurements\" and r._field == \"simaster_voltage\")\n|>last()"
    }
   ]
  },
  {
   "title": "L2 Voltage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"pv_data\")\n|>range(start:-10m)\n|>filter(fn: (r) => r._measurement == \"ac_measurements\" and r._field == \"sislave1_voltage\")\n|>last()"
    }
   ]
  },
  {
   "title": "Grid Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"pv_data\")\n|>range(start:-1d)\n|>filter(fn: (r) => r._measurement == \"ac_measurements\" and r._field == \"frequency\")\n|>last()"
    }
   ]
  },
  { "title": "Battery Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "SOC",
   "type": "stat",
   "description": "Most recent battery state of charge reading",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket:\"pv_data\")\n|>range(start:-30m)\n|>filter(fn: (r) => r._measurement == \"battery_measurements\" and r._field == \"soc\")\n|>last()"
    }
   ]
  },
  {
   "title": "Current Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"pv_data\")\n|>range(start:-1d)\n|>filter(fn: (r) => r._measurement == \"battery_measurements\" and r._field == \"voltage\")\n|>last()"
    }
   ]
  },
  {
   "title": "Current Battery Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"pv_data\")\n|>range(start:-1d)\n|>filter(fn: (r) => r._measurement == \"battery_measurements\" and r._field == \"temp\")\n|>last()"
    }
   ]
  },
  { "title": "Inverter Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Sunny Island Slave 1 Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "get", "keyName": "status_sunnyisland_slave1", "type": "command" }
   ]
  },
  {
   "title": "Sunny Island Master Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "get", "keyName": "status_sunnyisland_master", "type": "command" }
   ]
  },
  {
   "title": "Sunny Boy 1 Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "get", "keyName": "health_sunnyboy1", "type": "command" }
   ]
  },
  {
   "title": "Sunny Boy 2 Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "get", "keyName": "health_sunnyboy2", "type": "command" }
   ]
  }
 ]
}